# Generated by Django 3.2.4 on 2021-06-25 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='registration_time',
        ),
        migrations.RemoveField(
            model_name='book',
            name='username_register',
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Book name'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_year',
            field=models.IntegerField(null=True, verbose_name='year of book publish'),
        ),
        migrations.AddField(
            model_name='book',
            name='record_date',
            field=models.DateField(null=True, verbose_name='Time to record book'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('F', 'Free'), ('B', 'borrowed'), ('D', 'deprecated')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='update time Book information'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.author'),
        ),
    ]
