# Generated by Django 3.2.4 on 2021-07-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210625_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'کتاب', 'verbose_name_plural': 'کتاب ها'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
