# Generated by Django 3.2.4 on 2021-06-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.ImageField(default=20, upload_to='', verbose_name='credit'),
        ),
    ]
