# Generated by Django 3.2.4 on 2021-06-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.IntegerField(default=20, verbose_name='credit'),
        ),
    ]
